### ISSUE TITLE
Fix for search/wishlist UI/compactness?

### ISSUE THREAD

**Issue by sunlightspectre** [DukeDukeEm/DukesCleanSteamUI#1]
Hello there, Duke,

Thanks for all your hard work. I much prefer your solution to OldGlory, which - while praiseworthy! - is too extra for my tastes.  
I find the new steam search/wishlist UI absolutely awful. There are nine rows I need to scroll down just to get to the tag search function, and adding multiple tags appears to be more difficult. Furthermore, search results are humongous, have different colour-coding compared to wishlist or store page results, and auto-expand while scrolling down. 

Add in that scrolling is automatic and there's no page-function, and you have an experience that's pretty much unusable when you have worse internet than you did in the nineties, in a 'first-world' country. c: 

I imagine you're probably busy with other things, but I'd like to know what you'd recommend, or can be done, for the new store/search UI, if anything. Thank you very kindly..!

**Comment by Duke-M-commits** [comment]
Dear sunlightspectre, 

sorry for the really really long wait on my answer, I must had overseen your comment.
Most of Steams presence is rendered as their web-application. So the search/wishlist you're referring to isn't something the Steam skinning engine has access to (as far as I know). I only modify the 'local' part of the UI, the easiest way to distinguish them would be: everything what can be accessed in a normal webbrowser isn't local.

Thank you for your kind words :)

PS: my modification is actually really small, I do not try to reinvent the UI, I just get the 'ads' out, Valve may name them 'news', but the way they implemented them shows that their intentions aren't just about making the UX better for the users.

**Comment by sunlightspectre** [comment]
Dear Duke,

Thank you for the kind response. Don't worry; it's quite busy, and I have had trouble getting github to work properly as of late. I understand full well how time can disappear! c: Anyway, thanks for going over the technical bits - I wondered when I tried to do something about it myself and couldn't find any way to do so... So it goes, huh?

Anyway, I couldn't agree more - I hope all is well with you, I'll be closing this issue. Best!
